FILE_PATH = "LabShare/data/all/json/"
NON_GERMAN_FILE_PATH = "LabShare/data/non_german_files.txt"
CLEAN_FILE_PREFIX = "filtered_"
NON_GERMAN_FILE_PATH = "LabShare/data/non_german_files.txt"
SHARE_SPACE_FOLDER_PATH = "LabShare/data/group_bitcuda5/"
